# Static Islamic content for HB Eid ul Adha app.
# Authentic Sunnah, Qurbani guide, Takbeer, and Duas — provided in
# Arabic with Urdu + English translations and Hadith references.

EID_INFO = {
    "name": "Eid ul Adha",
    "tagline": "Authentic Sunnah & Qurbani Guide",
    # Approximate Gregorian dates (10 Dhul-Hijjah).
    "upcoming_dates": [
        "2026-05-27",
        "2027-05-17",
        "2028-05-05",
        "2029-04-24",
    ],
}

SUNNAH_ITEMS = [
    {
        "id": "ghusl",
        "title_en": "Ghusl (Ritual Bath)",
        "title_ur": "غسل کرنا",
        "title_ar": "الاغتسال",
        "arabic": "كان ابن عمر رضي الله عنهما يغتسل يوم الفطر قبل أن يغدو إلى المصلى.",
        "urdu": "حضرت ابن عمر رضی اللہ عنہما عید کے دن عیدگاہ جانے سے پہلے غسل کرتے تھے۔",
        "english": "Ibn 'Umar (RA) used to perform Ghusl on the day of Eid before going to the prayer ground.",
        "reference": "Muwatta Imam Malik 428",
        "icon": "water-outline",
    },
    {
        "id": "miswak",
        "title_en": "Use Miswak",
        "title_ur": "مسواک کرنا",
        "title_ar": "السواك",
        "arabic": "السِّوَاكُ مَطْهَرَةٌ لِلْفَمِ مَرْضَاةٌ لِلرَّبِّ",
        "urdu": "مسواک منہ کی پاکیزگی اور رب کی رضامندی کا ذریعہ ہے۔",
        "english": "Miswak purifies the mouth and pleases the Lord.",
        "reference": "Sahih al-Bukhari (Mu'allaq); Nasa'i 5",
        "icon": "leaf-outline",
    },
    {
        "id": "best-clothes",
        "title_en": "Wear Your Best Clothes",
        "title_ur": "اچھے کپڑے پہننا",
        "title_ar": "لبس أحسن الثياب",
        "arabic": "كان النبي صلى الله عليه وسلم يلبس أحسن ثيابه في العيدين والجمعة.",
        "urdu": "نبی کریم ﷺ عیدین اور جمعہ کے دن اپنے بہترین کپڑے پہنتے تھے۔",
        "english": "The Prophet ﷺ would wear his best clothes on the two Eids and on Friday.",
        "reference": "Sahih Ibn Khuzaymah 1765",
        "icon": "shirt-outline",
    },
    {
        "id": "perfume",
        "title_en": "Apply Itr (Perfume)",
        "title_ur": "عطر لگانا",
        "title_ar": "التطيب",
        "arabic": "كان رسول الله صلى الله عليه وسلم يحب الطيب ولا يرد طيبًا.",
        "urdu": "نبی کریم ﷺ خوشبو پسند فرماتے تھے اور خوشبو کو رد نہیں فرماتے تھے۔",
        "english": "The Prophet ﷺ loved fragrance and never refused perfume when offered.",
        "reference": "Shama'il al-Tirmidhi 211",
        "icon": "flower-outline",
    },
    {
        "id": "walk-to-eidgah",
        "title_en": "Walk to Eidgah",
        "title_ur": "پیدل عیدگاہ جانا",
        "title_ar": "المشي إلى المصلى",
        "arabic": "من السنة أن تخرج إلى العيد ماشيًا.",
        "urdu": "سنت یہ ہے کہ آدمی عیدگاہ پیدل جائے۔",
        "english": "It is from the Sunnah to walk to the Eid prayer.",
        "reference": "Sunan al-Tirmidhi 530",
        "icon": "walk-outline",
    },
    {
        "id": "different-routes",
        "title_en": "Take Different Routes",
        "title_ur": "آنے جانے کا راستہ بدلنا",
        "title_ar": "مخالفة الطريق",
        "arabic": "كان النبي صلى الله عليه وسلم إذا كان يوم عيد خالف الطريق.",
        "urdu": "نبی کریم ﷺ عید کے دن (عیدگاہ) آنے اور جانے کا راستہ بدل لیا کرتے تھے۔",
        "english": "On the day of Eid, the Prophet ﷺ would take different routes going and returning.",
        "reference": "Sahih al-Bukhari 986",
        "icon": "git-branch-outline",
    },
    {
        "id": "takbeer-on-way",
        "title_en": "Recite Takbeer Loudly",
        "title_ur": "راستے میں بلند آواز سے تکبیر پڑھنا",
        "title_ar": "رفع التكبير",
        "arabic": "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ لَا إِلَهَ إِلَّا اللَّهُ وَاللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ وَلِلَّهِ الْحَمْدُ",
        "urdu": "عیدگاہ کی طرف جاتے ہوئے بلند آواز سے تکبیرات پڑھنا سنت ہے۔",
        "english": "It is Sunnah to recite Takbeer loudly while walking to the Eid prayer (Eid al-Adha).",
        "reference": "Musannaf Ibn Abi Shaybah 5621",
        "icon": "megaphone-outline",
    },
    {
        "id": "eat-after-prayer",
        "title_en": "Eat After Eid Prayer",
        "title_ur": "نماز کے بعد کھانا",
        "title_ar": "الأكل بعد الصلاة",
        "arabic": "كان النبي صلى الله عليه وسلم لا يطعم يوم النحر حتى يرجع فيأكل من أضحيته.",
        "urdu": "نبی کریم ﷺ عید الاضحیٰ کے دن نماز سے پہلے کچھ نہیں کھاتے تھے اور لوٹ کر اپنی قربانی کے گوشت سے کھاتے تھے۔",
        "english": "On Eid al-Adha, the Prophet ﷺ would not eat until he returned (from prayer) and ate from his sacrifice.",
        "reference": "Sunan al-Tirmidhi 542",
        "icon": "restaurant-outline",
    },
    {
        "id": "qurbani-adab",
        "title_en": "Sacrifice With Excellence",
        "title_ur": "احسان کے ساتھ قربانی",
        "title_ar": "إحسان الذبح",
        "arabic": "إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ، فَإِذَا قَتَلْتُمْ فَأَحْسِنُوا الْقِتْلَةَ، وَإِذَا ذَبَحْتُمْ فَأَحْسِنُوا الذَّبْحَ، وَلْيُحِدَّ أَحَدُكُمْ شَفْرَتَهُ، وَلْيُرِحْ ذَبِيحَتَهُ.",
        "urdu": "بے شک اللہ نے ہر چیز میں احسان فرض کیا ہے، پس جب ذبح کرو تو اچھے طریقے سے ذبح کرو، اپنی چھری تیز کرو اور جانور کو راحت پہنچاؤ۔",
        "english": "Allah has prescribed excellence in all things. When you slaughter, do so in the best manner — sharpen your blade and ease the animal.",
        "reference": "Sahih Muslim 1955",
        "icon": "ribbon-outline",
    },
]

QURBANI_GUIDE = {
    "rules": [
        {
            "title_en": "Who Must Sacrifice",
            "title_ur": "کس پر واجب ہے",
            "body_en": "Qurbani is wajib upon every sane, adult Muslim (male or female) who possesses wealth equal to or above the Nisab (the value of 87.48g of gold or 612.36g of silver) beyond their basic needs, on the days of Eid al-Adha (10th, 11th, and 12th of Dhul-Hijjah).",
            "body_ur": "ہر عاقل، بالغ مسلمان (مرد یا عورت) پر قربانی واجب ہے جس کے پاس بنیادی ضروریات سے زائد نصاب (87.48 گرام سونا یا 612.36 گرام چاندی کی قیمت) کے برابر مال موجود ہو، 10، 11 اور 12 ذو الحجہ کے دنوں میں۔",
        },
        {
            "title_en": "Time of Qurbani",
            "title_ur": "قربانی کا وقت",
            "body_en": "Qurbani begins after the Eid prayer on 10th Dhul-Hijjah and continues until sunset on 12th Dhul-Hijjah. Sacrificing before the Eid prayer is not valid.",
            "body_ur": "قربانی 10 ذو الحجہ کو نمازِ عید کے بعد شروع ہوتی ہے اور 12 ذو الحجہ غروبِ آفتاب تک جاری رہتی ہے۔ نمازِ عید سے پہلے ذبح کرنا درست نہیں۔",
        },
        {
            "title_en": "Nisab Threshold",
            "title_ur": "نصاب",
            "body_en": "If you own gold/silver, cash, business stock, or savings equal to the Nisab beyond essentials, Qurbani becomes obligatory.",
            "body_ur": "اگر آپ کے پاس ضروریات سے زائد سونا، چاندی، نقد رقم یا مالِ تجارت نصاب کے برابر ہو، تو قربانی واجب ہے۔",
        },
    ],
    "animal_conditions": [
        {
            "title_en": "Minimum Age",
            "title_ur": "کم از کم عمر",
            "body_en": "Sheep/goat: 1 lunar year (or 6 months if it looks like a one-year-old). Cow/buffalo: 2 lunar years. Camel: 5 lunar years.",
            "body_ur": "بکری/بھیڑ: ایک سال (یا چھ ماہ کا جو ایک سال کا لگے)۔ گائے/بھینس: دو سال۔ اونٹ: پانچ سال۔",
        },
        {
            "title_en": "Health & Soundness",
            "title_ur": "صحت و سلامتی",
            "body_en": "The animal must be free from major defects: not blind, severely lame, visibly emaciated, or with no horn broken from the root, no severed ear, etc.",
            "body_ur": "جانور بڑے عیب سے پاک ہو: اندھا نہ ہو، نمایاں لنگڑا نہ ہو، انتہائی کمزور نہ ہو، سینگ جڑ سے ٹوٹا یا کان کٹا نہ ہو۔",
        },
        {
            "title_en": "Disqualifying Defects",
            "title_ur": "عیوب جن سے قربانی جائز نہیں",
            "body_en": "An animal that is one-eyed, lame to the point it cannot walk to the slaughter, sick with obvious illness, or extremely emaciated is not acceptable for Qurbani.",
            "body_ur": "ایک آنکھ سے اندھا، اتنا لنگڑا کہ ذبح کی جگہ تک چل نہ سکے، ظاہری بیمار یا بہت زیادہ کمزور جانور کی قربانی جائز نہیں۔",
        },
    ],
    "method": [
        {
            "step": 1,
            "title_en": "Niyyah (Intention)",
            "title_ur": "نیت",
            "body_en": "Make a sincere intention in your heart that this sacrifice is solely for the pleasure of Allah, following the Sunnah of Ibrahim (AS) and Muhammad ﷺ.",
            "body_ur": "دل میں خالص نیت کریں کہ یہ قربانی صرف اللہ کی رضا کے لیے، حضرت ابراہیم علیہ السلام اور نبی کریم ﷺ کی سنت پر ہے۔",
        },
        {
            "step": 2,
            "title_en": "Sharpen the Blade",
            "title_ur": "چھری تیز کرنا",
            "body_en": "Sharpen the knife away from the animal's sight. A sharp blade is mercy to the animal and a clear Sunnah.",
            "body_ur": "جانور کی نظر سے دور چھری تیز کریں۔ تیز چھری جانور پر رحم اور صریح سنت ہے۔",
        },
        {
            "step": 3,
            "title_en": "Face the Qibla",
            "title_ur": "قبلہ رخ کرنا",
            "body_en": "Lay the animal gently on its left side facing the Qibla. Avoid frightening or hurting it before slaughter.",
            "body_ur": "جانور کو نرمی سے بائیں پہلو پر قبلہ رخ لٹائیں۔ ذبح سے پہلے جانور کو ڈرانے یا اذیت دینے سے گریز کریں۔",
        },
        {
            "step": 4,
            "title_en": "Recite the Dua",
            "title_ur": "دعا پڑھنا",
            "body_en": "Recite: 'Bismillahi Allahu Akbar' — then complete with the Qurbani dua (see Duas tab).",
            "body_ur": "پڑھیں: 'بسم اللہ اللہ اکبر' — پھر قربانی کی مکمل دعا پڑھیں (دعاؤں والے ٹیب میں دیکھیں)۔",
        },
        {
            "step": 5,
            "title_en": "Slaughter Swiftly",
            "title_ur": "جلدی ذبح کرنا",
            "body_en": "Cut the throat, windpipe, and the two jugular veins in one swift motion. Do not break the neck or skin until the animal is fully still.",
            "body_ur": "حلق، سانس کی نالی اور دونوں رگیں ایک ہی تیز حرکت میں کاٹیں۔ جانور کے مکمل ساکن ہونے سے پہلے کھال یا گردن نہ توڑیں۔",
        },
        {
            "step": 6,
            "title_en": "Distribute the Meat",
            "title_ur": "گوشت کی تقسیم",
            "body_en": "It is Mustahabb to divide the meat into three parts: one third for your family, one third for relatives and friends, and one third for the poor and needy.",
            "body_ur": "مستحب ہے کہ گوشت تین حصوں میں تقسیم کیا جائے: ایک تہائی اہلِ خانہ کے لیے، ایک تہائی رشتہ داروں اور دوستوں کے لیے، اور ایک تہائی غریبوں اور مسکینوں کے لیے۔",
        },
    ],
}

TAKBEER = {
    "title_en": "Takbeer-e-Tashreeq",
    "title_ur": "تکبیرِ تشریق",
    "arabic": "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لَا إِلَهَ إِلَّا اللَّهُ، وَاللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، وَلِلَّهِ الْحَمْدُ",
    "transliteration": "Allahu Akbar, Allahu Akbar, La ilaha illa Allah, wa Allahu Akbar, Allahu Akbar, wa lillahil-hamd",
    "urdu": "اللہ سب سے بڑا ہے، اللہ سب سے بڑا ہے، اللہ کے سوا کوئی معبود نہیں، اور اللہ سب سے بڑا ہے، اللہ سب سے بڑا ہے، اور سب تعریف اللہ ہی کے لیے ہے۔",
    "english": "Allah is the Greatest, Allah is the Greatest, there is no deity except Allah, and Allah is the Greatest, Allah is the Greatest, and to Allah belongs all praise.",
    "reference": "Recited from Fajr of 9th Dhul-Hijjah to Asr of 13th Dhul-Hijjah after every fard salah. — Musannaf Ibn Abi Shaybah 5633",
}

DUA_CATEGORIES = [
    {"id": "eid", "name_en": "Eid Duas", "name_ur": "عید کی دعائیں", "icon": "moon-outline"},
    {"id": "qurbani", "name_en": "Qurbani Dua", "name_ur": "قربانی کی دعا", "icon": "ribbon-outline"},
    {"id": "morning", "name_en": "Morning Azkar", "name_ur": "صبح کے اذکار", "icon": "sunny-outline"},
    {"id": "evening", "name_en": "Evening Azkar", "name_ur": "شام کے اذکار", "icon": "partly-sunny-outline"},
    {"id": "eating", "name_en": "Eating Duas", "name_ur": "کھانے کی دعائیں", "icon": "restaurant-outline"},
    {"id": "traveling", "name_en": "Traveling Dua", "name_ur": "سفر کی دعا", "icon": "airplane-outline"},
]

DUAS_BY_CATEGORY = {
    "eid": [
        {
            "id": "eid-greeting",
            "title_en": "Eid Greeting (Sahabah)",
            "title_ur": "صحابہ کا عید پر مبارکباد دینا",
            "arabic": "تَقَبَّلَ اللَّهُ مِنَّا وَمِنْكُمْ",
            "transliteration": "Taqabbal-Allahu minna wa minkum",
            "english": "May Allah accept (the worship) from us and from you.",
            "urdu": "اللہ ہماری اور آپ کی (عبادات) قبول فرمائے۔",
            "reference": "Fath al-Bari 2/446",
        },
        {
            "id": "eid-takbeer",
            "title_en": "Takbeer of Eid",
            "title_ur": "عید کی تکبیر",
            "arabic": "اللَّهُ أَكْبَرُ كَبِيرًا وَالْحَمْدُ لِلَّهِ كَثِيرًا وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلًا",
            "transliteration": "Allahu Akbaru kabira, walhamdulillahi kathira, wa subhan-Allahi bukratan wa asila",
            "english": "Allah is the Greatest in greatness, and abundant praise be to Allah, and glory to Allah morning and evening.",
            "urdu": "اللہ سب سے بڑا ہے بڑا، اور اللہ کے لیے بہت زیادہ تعریف ہے، اور پاکی ہے اللہ کے لیے صبح و شام۔",
            "reference": "Sahih Muslim 601",
        },
    ],
    "qurbani": [
        {
            "id": "qurbani-dua",
            "title_en": "Dua at the Time of Sacrifice",
            "title_ur": "قربانی کے وقت کی دعا",
            "arabic": "إِنِّي وَجَّهْتُ وَجْهِيَ لِلَّذِي فَطَرَ السَّمَاوَاتِ وَالْأَرْضَ حَنِيفًا وَمَا أَنَا مِنَ الْمُشْرِكِينَ، إِنَّ صَلَاتِي وَنُسُكِي وَمَحْيَايَ وَمَمَاتِي لِلَّهِ رَبِّ الْعَالَمِينَ، لَا شَرِيكَ لَهُ وَبِذَلِكَ أُمِرْتُ وَأَنَا مِنَ الْمُسْلِمِينَ. اللَّهُمَّ مِنْكَ وَلَكَ. بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ",
            "transliteration": "Inni wajjahtu wajhiya lilladhi fataras-samawati wal-arda hanifan wa ma ana minal-mushrikin. Inna salati wa nusuki wa mahyaya wa mamati lillahi rabbil-'alamin, la sharika lah, wa bidhalika umirtu wa ana minal-muslimin. Allahumma minka wa lak. Bismillahi wAllahu Akbar.",
            "english": "I have turned my face sincerely to the One who created the heavens and the earth, and I am not of the polytheists. Indeed, my prayer, my sacrifice, my life and my death are for Allah, Lord of the worlds, with no partner. Thus I am commanded, and I am of those who submit. O Allah, this is from You and for You. In the Name of Allah, and Allah is the Greatest.",
            "urdu": "میں نے یکسوئی کے ساتھ اپنا رخ اُسی کی طرف کر لیا جس نے آسمان اور زمین کو پیدا کیا، اور میں مشرکوں میں سے نہیں ہوں۔ بے شک میری نماز، میری قربانی، میرا جینا اور میرا مرنا اللہ ہی کے لیے ہے، جو سارے جہانوں کا رب ہے، اس کا کوئی شریک نہیں۔ یہی مجھے حکم دیا گیا ہے اور میں مسلمانوں میں سے ہوں۔ اے اللہ! یہ تیری ہی طرف سے ہے اور تیرے ہی لیے ہے۔ اللہ کے نام سے، اور اللہ سب سے بڑا ہے۔",
            "reference": "Sunan Abu Dawud 2795",
        },
    ],
    "morning": [
        {
            "id": "ayatul-kursi",
            "title_en": "Ayat al-Kursi (mornings & evenings)",
            "title_ur": "آیت الکرسی",
            "arabic": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ...",
            "transliteration": "Allahu la ilaha illa huwal-hayyul-qayyum...",
            "english": "Whoever recites Ayat al-Kursi in the morning will be protected from jinn until evening, and whoever recites it in the evening will be protected until morning.",
            "urdu": "جو صبح آیت الکرسی پڑھے، شام تک اور جو شام پڑھے، صبح تک جنّات سے محفوظ رہتا ہے۔",
            "reference": "Sahih Targhib 655",
        },
        {
            "id": "asbahna",
            "title_en": "Morning Remembrance",
            "title_ur": "صبح کا ذکر",
            "arabic": "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
            "transliteration": "Asbahna wa asbahal-mulku lillah, walhamdulillah, la ilaha illa Allah wahdahu la sharika lah",
            "english": "We have entered the morning and so has the whole kingdom of Allah. All praise is for Allah. There is no god but Allah, alone, with no partner.",
            "urdu": "ہم نے اور ساری کائنات نے اللہ ہی کے لیے صبح کی۔ ساری تعریف اللہ کے لیے ہے۔ اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔",
            "reference": "Sahih Muslim 2723",
        },
    ],
    "evening": [
        {
            "id": "amsayna",
            "title_en": "Evening Remembrance",
            "title_ur": "شام کا ذکر",
            "arabic": "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ",
            "transliteration": "Amsayna wa amsal-mulku lillah, walhamdulillah, la ilaha illa Allah wahdahu la sharika lah",
            "english": "We have entered the evening and so has the whole kingdom of Allah. All praise is for Allah. There is no god but Allah, alone, with no partner.",
            "urdu": "ہم نے اور ساری کائنات نے اللہ ہی کے لیے شام کی۔ ساری تعریف اللہ کے لیے ہے۔ اللہ کے سوا کوئی معبود نہیں، وہ اکیلا ہے، اس کا کوئی شریک نہیں۔",
            "reference": "Sahih Muslim 2723",
        },
    ],
    "eating": [
        {
            "id": "before-eating",
            "title_en": "Before Eating",
            "title_ur": "کھانے سے پہلے",
            "arabic": "بِسْمِ اللَّهِ",
            "transliteration": "Bismillah",
            "english": "In the Name of Allah.",
            "urdu": "اللہ کے نام سے۔",
            "reference": "Sunan Abu Dawud 3767",
        },
        {
            "id": "after-eating",
            "title_en": "After Eating",
            "title_ur": "کھانے کے بعد",
            "arabic": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
            "transliteration": "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
            "english": "All praise is for Allah who fed me this and provided it for me without any might or power on my part.",
            "urdu": "تمام تعریفیں اللہ کے لیے ہیں، جس نے یہ مجھے کھلایا اور بغیر میری کسی طاقت اور قوت کے روزی دی۔",
            "reference": "Sunan Abi Dawud 4023",
        },
    ],
    "traveling": [
        {
            "id": "travel-dua",
            "title_en": "Dua for Travel",
            "title_ur": "سفر کی دعا",
            "arabic": "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
            "transliteration": "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun",
            "english": "Glory is to Him who has subjected this for us, and we could never have done it by ourselves, and to our Lord we will surely return.",
            "urdu": "پاک ہے وہ ذات جس نے ہمارے لیے یہ مسخر کیا، حالانکہ ہم اسے قابو میں لانے والے نہ تھے، اور بے شک ہم اپنے رب کی طرف لوٹنے والے ہیں۔",
            "reference": "Sunan Abi Dawud 2602",
        },
    ],
}

DAILY_HADITHS = [
    {
        "arabic": "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
        "english": "Actions are by intentions, and every person will have what they intended.",
        "urdu": "اعمال کا دار و مدار نیتوں پر ہے، اور ہر شخص کو وہی ملے گا جس کی اس نے نیت کی۔",
        "reference": "Sahih al-Bukhari 1",
    },
    {
        "arabic": "مَا عَمِلَ ابْنُ آدَمَ يَوْمَ النَّحْرِ عَمَلًا أَحَبَّ إِلَى اللَّهِ مِنْ إِهْرَاقِ الدَّمِ",
        "english": "No deed of the son of Adam on the day of sacrifice is more beloved to Allah than the shedding of blood (of the qurbani animal).",
        "urdu": "قربانی کے دن ابنِ آدم کا کوئی عمل اللہ کو خونِ قربانی بہانے سے زیادہ پسند نہیں۔",
        "reference": "Sunan al-Tirmidhi 1493",
    },
    {
        "arabic": "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
        "english": "A Muslim is one from whose tongue and hand other Muslims are safe.",
        "urdu": "مسلمان وہ ہے جس کی زبان اور ہاتھ سے دوسرے مسلمان محفوظ رہیں۔",
        "reference": "Sahih al-Bukhari 10",
    },
    {
        "arabic": "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
        "english": "Whoever believes in Allah and the Last Day should speak good or remain silent.",
        "urdu": "جو شخص اللہ اور آخرت پر ایمان رکھتا ہے، اسے چاہیے کہ اچھی بات کہے یا خاموش رہے۔",
        "reference": "Sahih al-Bukhari 6018",
    },
    {
        "arabic": "الدُّعَاءُ هُوَ الْعِبَادَةُ",
        "english": "Dua is itself worship.",
        "urdu": "دعا ہی عبادت ہے۔",
        "reference": "Sunan al-Tirmidhi 2969",
    },
    {
        "arabic": "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ",
        "english": "Indeed, Allah is Beautiful and loves beauty.",
        "urdu": "بے شک اللہ خوبصورت ہے اور خوبصورتی کو پسند کرتا ہے۔",
        "reference": "Sahih Muslim 91",
    },
    {
        "arabic": "خَيْرُكُمْ خَيْرُكُمْ لِأَهْلِهِ",
        "english": "The best of you are those who are best to their families.",
        "urdu": "تم میں سب سے بہتر وہ ہے جو اپنے گھر والوں کے ساتھ سب سے بہتر ہو۔",
        "reference": "Sunan al-Tirmidhi 3895",
    },
]
